import React from 'react'
import Navbar from '../Component/Navbar'

const AddJournal = () => {
    const [journal, setJournal] = React.useState({
        title: '',
        author: '',
        category: '',
        publishYear: '',
        issn: '',
        volume: '',
        issue: '',
        publicationFrequency: '',
        publisher: '',
        coverImage: '',
        description: '',
        location: '',
    });

    const handleChange = (e) => {
        const { name, value } = e.target;
        setJournal(prev => ({ ...prev, [name]: value }));
    };

    const handleSubmit = async (e) => {
        e.preventDefault();

        if (!journal.title || !journal.author || !journal.category || !journal.publishYear || !journal.issn || !journal.volume || !journal.issue || !journal.publicationFrequency) {
            alert('Please fill in all required fields.');
            return;
        }

        const newJournal = {
            // itemId will usually be generated by backend, not front-end
            title: journal.title,
            author: journal.author,
            category: journal.category,
            publishYear: parseInt(journal.publishYear),
            status: "AVAILABLE",
            coverImage: journal.coverImage || null,
            description: journal.description,
            location: journal.location || null,
            itemType: "Journal",
            issn: journal.issn,
            volume: journal.volume,
            issue: journal.issue,
            publicationFrequency: journal.publicationFrequency,
            publisher: journal.publisher,
        };

        console.log('Submitting payload:', newJournal);

        try {
            const response = await fetch(`${import.meta.env.VITE_BASE_URL}${import.meta.env.VITE_JOURNALS_API}`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(newJournal),
            });

            if (response.ok) {
                alert('Journal added successfully');
                setJournal({
                    title: '',
                    author: '',
                    category: '',
                    publishYear: '',
                    issn: '',
                    volume: '',
                    issue: '',
                    publicationFrequency: '',
                    publisher: '',
                    coverImage: '',
                    description: '',
                    location: '',
                });
            } else {
                const errorData = await response.json().catch(() => ({}));
                alert('Failed to add journal: ' + (errorData.message || response.statusText));
            }
        } catch (error) {
            console.log('Error adding journal:', error);
            alert('Error adding journal');
        }
    };

    return (
        <div className="min-h-screen bg-base-200">
            <Navbar />
            <div className="flex flex-col items-center justify-center mt-10">
                <h1 className="text-4xl font-bold mb-6">Add Journal</h1>
                <div className="card w-full max-w-md bg-base-100 shadow-xl">
                    <figure className="px-10 pt-10">
                        <img
                            src={journal.coverImage || "https://via.placeholder.com/300x400?text=No+Cover"}
                            alt="Journal Cover"
                            className="rounded-xl w-32 h-32 object-cover"
                        />
                    </figure>
                    <div className="card-body items-center text-responsive">
                        <form className="w-full flex flex-col gap-4" onSubmit={handleSubmit}>
                            <input type="text" name="title" placeholder="Journal Title *" className="input input-bordered w-full" onChange={handleChange} value={journal.title} required />
                            <input type="text" name="author" placeholder="Author *" className="input input-bordered w-full" onChange={handleChange} value={journal.author} required />
                            <input type="text" name="category" placeholder="Category *" className="input input-bordered w-full" onChange={handleChange} value={journal.category} required />
                            <input type="number" name="publishYear" placeholder="Publish Year *" className="input input-bordered w-full" onChange={handleChange} value={journal.publishYear} required />
                            <input type="text" name="issn" placeholder="ISSN *" className="input input-bordered w-full" onChange={handleChange} value={journal.issn} required />
                            <input type="text" name="volume" placeholder="Volume *" className="input input-bordered w-full" onChange={handleChange} value={journal.volume} required />
                            <input type="text" name="issue" placeholder="Issue *" className="input input-bordered w-full" onChange={handleChange} value={journal.issue} required />
                            <input type="text" name="publicationFrequency" placeholder="Publication Frequency *" className="input input-bordered w-full" onChange={handleChange} value={journal.publicationFrequency} required />
                            <input type="text" name="publisher" placeholder="Publisher" className="input input-bordered w-full" onChange={handleChange} value={journal.publisher} />
                            <input type="url" name="coverImage" placeholder="Cover Image URL" className="input input-bordered w-full" onChange={handleChange} value={journal.coverImage} />
                            <textarea name="description" placeholder="Description" className="textarea textarea-bordered w-full" onChange={handleChange} value={journal.description} rows="3" />
                            <input type="text" name="location" placeholder="Location" className="input input-bordered w-full" onChange={handleChange} value={journal.location} />
                            <button type="submit" className="btn btn-primary w-full">Add Journal</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default AddJournal
